### ISSUE TITLE
Gerber files format specifier

### ISSUE THREAD

**Issue by JozefHumaj** [pcb2gcode/pcb2gcode#114]
In case i use decimal on 4 places i got an error code 62097 while processing input files. Any workaround?
"format_specifier": {
                "decimal": 4,
                "integer": 3
            },

**Comment by eyal0** [comment]
Can you send a log of the output?

**Comment by eyal0** [comment]
Never heard back.  I'm closing this.  Re-open it if you want to keep debugging.  I think that the error that you saw was from gerbv, not from pcb2gcode.  Maybe try a newer version of libgerbv?
