### ISSUE TITLE
TSP path optimization missing

### ISSUE THREAD

**Issue by koppi** [pcb2gcode/pcb2gcode#12]
I wrote a small Python script that optimizes the excellon drill file's path, see: https://github.com/curtacircuitos/pcb-tools/issues/30

It would be super cool, if pcb2gcode could support TSP path optimization.

**Comment by Corna** [comment]
I'm working on a simple nearest neighbour implementation, and it works quite well right now
I'll shortly create a new test branch for it

**Comment by koppi** [comment]
:thumbsup:

**Comment by koppi** [comment]
please report back here, when it's ready to test.

**Comment by Corna** [comment]
Here it is
commit e3c49955ae3eea3cc9e10d8c1b3c638e8eb7d733 (in the new branch [drill_optimisation](https://github.com/pcb2gcode/pcb2gcode/tree/drill_optimisation))
Read the commit description for more info

**Comment by koppi** [comment]
I just tested it with my arduino-shield, works perfect, thanks a lot! :100:

**Comment by Corna** [comment]
Can you please report the path before and after the optimisation?

**Comment by Corna** [comment]
Can you please paste here the paths before and after the optimisation?

**Comment by koppi** [comment]
Drill path without optimization:
![20150611-001](https://cloud.githubusercontent.com/assets/9458631/8110992/64529012-105f-11e5-9fa2-5c57ea08ea0a.png)
Drill path with optimization:
![20150611-002](https://cloud.githubusercontent.com/assets/9458631/8110988/5e9dbdb8-105f-11e5-86d4-b2a1fa73a49e.png)

**Comment by Corna** [comment]
Thanks
Good, after some tests I'll merge it into the master branch

**Comment by Corna** [comment]
Merged

**Comment by matthijskooijman** [comment]
Thanks for this change, it was on my lists of annoyances to fix as well :-D

**Comment by corna** [comment]
You're welcome :-)
