### ISSUE TITLE
Add support for specifying a list of available drill sizes

### ISSUE THREAD

**Issue by eyal0** [pcb2gcode/pcb2gcode#128]
Issue tracking for: https://github.com/pcb2gcode/pcb2gcode/pull/120#issuecomment-386517707

**Comment by eyal0** [comment]
I'd like to discuss how best to implement this.

I think that it should be based on which drill sizes the user has.  If the user has 1/8 and 1/16, all the drilling sizes should be rounded to 1/8 and 1/16.  So the actual drill sizes needs to be an input.

Having the user specify a range for each one is a bit clunky.  I feel like it's too much to put it on a command line.  What if we just had the user provide a list of bit sizes, without a range?  And then pcb2gcode would round to the nearest drill bit size?

Is rounding to the closest the best answer?  Or should we always round to the bigger one?  Or to the smaller one?

Maybe the option could be something like: `--drills-available=<list of drill sizes>`

And then always round to the closest?

I want to find a balance where the option is useful but not too complicated to use.  As the PR is right now, the option seems too complicated to use.

**Comment by eyal0** [comment]
@kmjonsson and @laurivosandi , I added this issue to have a discussion about how to best implement this feature.

**Comment by kmjonsson** [comment]
Just to have the background about the PR.

It two options:
1. is the **drills-tolerance** that sets the basic rules for the diff of drill vs hole.
2. is the **drills-available** that in it's simplest form is just a list of availables drills.

I made 2 for the PR so that you can set a separate tolerance for each drill (if you want to).

1 should perhaps has an upper and lower limit as it's probably OK to have a drill that is 0.2 to big but perhaps not 0.2 to small.

One question we have to discuss is that to do if the drill does not fit ant of the available drills?

The PR just ignores drills that are outside. Then you can use whatever you find suitable for that size.

I have drills for 0.2mm -> 1.2mm in 0.1mm steps. And then a random set of bits up to ~3mm that fits my CNC. Sometimes I need to drill holes that are not in my standard set. Then I just drilla pilot hole and to the final drill outside the CNC with an regular drill.

**Comment by eyal0** [comment]
Why do you need tolerance? If you just provide a list of bits and use the closest value, will that provide enough functionality?

I don't want to overengineer a solution that will be complicated to use.

Did you have a situation where using the closest size drill bit wouldn't work? Both too big and too small are problems so I would think that closest match is a good solution.

Pilot holes are a feature that I've heard mentioned before, too. Also, some people would like to milldrill holes that are too big and regular drill the rest.

We should think of a solution that covers all these cases.

**Comment by kmjonsson** [comment]
I think a tolerance might be good so that a 9mm hole is not fitted into a 1mm drill just because it's the closest. At least not without a warning.

This feature could on the other hand replace the "one drill" feature as the result will be the same with the right input.

**Comment by eyal0** [comment]
I understand.  Also, I agree that this option will work instead of `onedrill`.

I want to think about the best way to implement this.

As I see it: Imagine that you have a CNC with a bunch of drill bits.  Maybe you have all size from 0.1, 0.2, 0.3,...,1.0.  For all holes up to, say, 1.05mm, you want to use those bits.  What do you do for everything greater than 1.05?  Either milldrill, meaning that you use the milling bit to mill out the holes.  That's one solution.  Or, maybe you want to just drill pilot holes for those big ones?  Or maybe pilot holes for all of them?

So how do can we specify all those situations?

First, I think that it's easy to specify drill bits.  You already know what you have so it's easy to list them: `--drill-bits=0.1,0.2,0.3...`.  Listing the tolerance for each one is more verbose and you'd probably just split the difference on each one.  0.05 for each in this case.

Then you need a way to specify what to do with the holes that are way too big or too small for those bits.  I don't think that tolerance is useful because what if you have a drill bit that is 0.1 and another 0.4 and you set tolerance to 0.1.  If you have to drill a hole that is 0.25 and you didn't put 0.25 in your list, the CNC is going to ask for 0.25 and you don't have it.  You're simply not going to be able to drill that hole.

For holes like that, maybe you want to use pilot holes?  Perhaps you don't have the right size bit for your CNC but you have a drill press with the right bit.  So you want pilot holes.  Cool.

Or possibly you want to milldrill if the hole is big enough.  You could say, beyond a certain size, take the milling bit and cut out the holes.

Hmm...

So maybe your approach is best!  `--drills-available` is a list of drill bits.  Either written as just a diameter or diameter with a tolerance.  If no tolerance is specified, we'll use the default tolerance which is `--drills-tolerance`.  And if no drills-tolerance is set then the tolerance is infinite, that is, we just use whichever drill bit is closest in size.

When we're looking for the drill to use, we pick the one that is closest in size.  If it fits the tolerance, we use that.  If not, then we just request the exact size (this is like how it works right now).

Finally, I want a way to do pilot holes and milldrill, because [that is a request that I've heard of](https://github.com/pcb2gcode/pcb2gcode/issues/45).  We'll have an option that will force milldrilling for any hole that is larger than a specified size.  I don't see a need to milldrill different ranges.  Just anything bigger than some value is milldrilled.

As for pilot holes, maybe just an option that says "drill pilot holes for anything that can't be drilled or milldrilled".  That is, it's out of tolerance, so no drill will suffice, and it's too small for milldrill.  And we'll need to provide a depth for the pilot holes.  And I'm not sure if pilot holes should be done with the isolator or with a drill.

Lots to do so I'll break it down:

1. Support drills and tolerance.  That is the original PR.  Everything outside of the tolerance gets drilled like normal.
2. Make an option to have milldrill only milldrill the big holes and ignore small holes.
3. Make an option to drill or mill pilot holes for holes that can't be drilled or milled.

Number 1 is the PR the original PR.  I'll start by looking at that.  I'll need to look at how it parses the option.  Now that we have supports for units, I want to use that so that drills can be specified like "0.3mm" or "125mils".  I would also like to be able to specify tolerance as a length (mm, inches, thou, etc.)

I'll take a look soon.  Thanks for al the work!

**Comment by kmjonsson** [comment]
I have started working on an better option parsing. I'll make an new PR of the even if it's not finished so you can look at it. I think it's a little more clean then the original PR.

**Comment by eyal0** [comment]
Okay.  Look at how I do inputs for options: https://github.com/pcb2gcode/pcb2gcode/blob/master/units.hpp#L305

If you just overload the >> and << operators, you will get parsing sort of for free.  You can use the Unit classes in there to handle all the numbers so that it will automatically know if the input is mm or inches or thou.
