### ISSUE TITLE
Howto use pcb2gcode --back feature?

### ISSUE THREAD

**Issue by koppi** [pcb2gcode/pcb2gcode#13]
Is the gerber file provided with ```--back``` supposted to be mirrored by Kicad, or is the mirroring done by pcb2gcode?

**Comment by koppi** [comment]
Oki, I figured it out – pcb2gcode mirrors the back gerber for me.

**Comment by Corna** [comment]
Yep, you can just export the back file from KiCad and pcb2gcode will handle it
