### ISSUE TITLE
When using milldrill code doesn't start the spindle

### ISSUE THREAD

**Issue by zazolabs** [pcb2gcode/pcb2gcode#20]
diff --git a/drill.cpp b/drill.cpp
    index 9e1970c..c73d6c7 100644
    --- a/drill.cpp
    +++ b/drill.cpp
    @@ -437,6 +437,7 @@ void ExcellonProcessor::export_ngc(const string outputname,     shared_ptr<Cutter> t
            << " (Feedrate)\n\n";
 
         of << "G00 Z" << target->zsafe * cfactor << endl;
    +    of << "M3      (Spindle on clockwise.)\n" << "\n";
     
         tiling->header( of );

**Comment by corna** [comment]
You're right, fixed in the latest commit (3b2083254b5185f386e1dd7f2a046f9348ffe6fd)
Thanks
