### ISSUE TITLE
"Allow-Dumb-Decisions" flag

### ISSUE THREAD

**Issue by a7hybnj2** [pcb2gcode/pcb2gcode#201]
This would just remove error checking. So, if I entered a zwork +5 and zsafe -5 I could. Would be useful in some odd machine setups and for laser users.  
And the title flag name was a joke. Would be more like ignore-warnings or something.

**Comment by a7hybnj2** [comment]
Wow, great! I just read through the pcb2gcode --help and it looks like most of my other suggestions are already implemented. So, my last suggestion is copy "pcb2gcode --help" to the wiki and man pages.

**Comment by eyal0** [comment]
Sorry to keep you waiting!  https://github.com/pcb2gcode/pcb2gcode/pull/221
