### ISSUE TITLE
cut-front logic is inverted

### ISSUE THREAD

**Issue by zazolabs** [pcb2gcode/pcb2gcode#21]
diff --git a/main.cpp b/main.cpp
    index 87b94b0..0ed03cb 100644
    --- a/main.cpp
    +++ b/main.cpp
    @@ -298,7 +298,7 @@ int main(int argc, char* argv[])
             {
                 string outline = vm["outline"].as<string>();                               //Filename
                 boost::shared_ptr<LayerImporter> importer(new GerberImporter(outline));
    -            board->prepareLayer("outline", importer, cutter, vm["cut-front"].as<bool>(),
    +            board->prepareLayer("outline", importer, cutter, !vm["cut-front"].as<bool>(),
                                     vm["mirror-absolute"].as<bool>());
     
                 cout << "DONE.\n";

**Comment by corna** [comment]
Fixed in 13a94b35623ceb918d4cf79181f5aa252ce614bd, thanks
