### ISSUE TITLE
Empty output depending on fill-outline=false

### ISSUE THREAD

**Issue by zazolabs** [pcb2gcode/pcb2gcode#22]
Hi,

If i set  fill-outline to false outline.ngc is generated ok
but back/front are empty, i guess it have something to do with 

    Warning: pcb2gcode hasn't been able to fulfill all clearance requirements and tried a best effort     approach instead. You may want to check the g-code output and possibly use a smaller milling width.
    Can't create 4 bridges on this layer, only 3 will be created.

if set to true output is correct. /as excepted no internal cutoff-s are created/

[millproject.txt](https://github.com/pcb2gcode/pcb2gcode/files/44046/millproject.txt)

**Comment by corna** [comment]
See issue #7 for the empty front/back, issue #18 for the internal cutoffs

**Comment by corna** [comment]
Btw, I'm working right now on the fill-outline option, I'm going to enable it by default

**Comment by zazolabs** [comment]
I'll take a deeper look at #7 and #18 but have to dig deeper to understand them.
