### ISSUE TITLE
install from git under Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by atmelino** [pcb2gcode/pcb2gcode#227]
(I need the latest version because the repository version does not work with pcb2gcodeGUI)
Install from git:
./configure fails with message
configure: error: Package requirements (librsvg-2.0 >= 2.0) were not met:
No package 'librsvg-2.0' found

this problem goes away once I run
sudo apt-get install librsvg2-dev

now I got version 1.3.2 and pcb2gcodeGUI works.

Maybe add librsvg2-dev to readme.md?

$ sudo apt-get install build-essential automake autoconf autoconf-archive libtool libboost-program-options-dev libgtkmm-2.4-dev gerbv git librsvg2-dev

**Comment by eyal0** [comment]
Yes!  Would you like to do that?  You can just edit that README file, even from within github, and make a a PR that I will approve.

**Comment by eyal0** [comment]
Look at you, a contributor now! Thanks for the help!
