### ISSUE TITLE
pcb2gcode won't run.

### ISSUE THREAD

**Issue by Hactar42** [pcb2gcode/pcb2gcode#232]
Problem with pcb2gcode-1.3.2-win32   Installed in Windows 10 Home. Ver:	10.0.17134 Build 17134

When I try to run pcb2gcode.exe: A small screen flashes quickly (I cannot read what it says) then the program quits.  Windows task manager does not show it running.

When I run pcb2gcode.exe as an administrator:  The screen turns totally black for a few seconds then the program quits.

I expected the program to run.  My system seems to be running perfectly with no problems with any  other applications.

I have a PCB design completed in Kicad pcbnew and need to convert it to grbl CNC router.

Can't attach any related files because the program never ran.

 Any advice or help would be much appreciated.

**Comment by eyal0** [comment]
No progress here in a long time.  I'll close this.

**Comment by eyal0** [comment]
This is fixed by b88a2fbd and 011336db and 6d15f726
