### ISSUE TITLE
Diagonal traces wider than they should

### ISSUE THREAD

**Issue by matthijskooijman** [pcb2gcode/pcb2gcode#27]
While reviewing my milling result, I noticed that my horizontal and vertical traces were narrower than the diagonal ones. I first thought this was inaccuracy in my CNC mill, but since it seemed to happen to all traces, and, looking back at earlier designs, there as well, I took a closer look at the generated gcode.

Here's at testcase with just a single trace, consisting of a diagonal and horizontal part: https://gist.github.com/matthijskooijman/7030a7f344aa362e82e6

The resulting gcode looks like this: 
![selection_008](https://cloud.githubusercontent.com/assets/194491/11843864/1b883a44-a40c-11e5-8e20-15e3cda0b235.png)

The trace should be 0.25mm wide. The red lines are 0.5mm wide, so it looks like the horizontal line is ok, but the diagonal line is too wide.

**Comment by corna** [comment]
This is (sadly) a known bug and, with the current implementation of surface.cpp, it is unfixable.
I don't like at all the implementation of the core functions but the only way to fix them is to switch to a vectorial approach, which is a rather big work and, at the moment, I don't have much spare time.
