### ISSUE TITLE
Wrong Default al-probevar value for Mach4

### ISSUE THREAD

**Issue by PhilNad** [pcb2gcode/pcb2gcode#29]
The manual specifies :

--al-probevar number 
custom Z probe code result variable. For example, LinuxCNC uses 5063 while Mach3, Mach4 and TurboCNC use 2002. If unspecified, 2002 will be used. This option is relevant only when --software=custom

In Mach4, the pound variable used for the Z probe code result is 5063 instead of 2002.

**Comment by corna** [comment]
You're right. Weird, I've tested it on a Mach4 simulator and it worked, perhaps it accepts 2002 for backwards compatibility.
Thanks for the bug report, I've fixed it in commit ebb89480f260641846b7ca31f5811d46664880fb
