### ISSUE TITLE
Wrong manual entry for --al-x and --al-y

### ISSUE THREAD

**Issue by PhilNad** [pcb2gcode/pcb2gcode#30]
In the manual its stated that:

--al-x unit 
the width of the probing on the X axis. Higher values increase the levelling precision but also increases the probing time (but not the milling time)

But by looking at the source code we can quickly see that the LOWER the value is, the more probe points will be generated.

XProbeDistRequired( options["al-x"].as<double>() * unitconv )
temp = round ( workareaLenX / XProbeDistRequired );

Same problem for --al-y

**Comment by corna** [comment]
Correct, thanks. Fixed in commit 8af905b65251d6dad46550bf4e52f179f6323337
