### ISSUE TITLE
Absolute tool change height only works in drill mode

### ISSUE THREAD

**Issue by christoph1703** [pcb2gcode/pcb2gcode#315]
Please fill this out:

pcb2gcode version (run pcb2gcode --version to see this):
2.0.0
Git commit: v2.0.0-102-g6b71101
Boost: 106501
Gerbv: 2.6.1

What did you try (include command-line arguments):
I set `zchange-absolute=1` and `zchange=0` in the millproject file.
No special arguments. 
`pcb2gcode --front cpu-test-F_Cu.gbr --outline cpu-test-Edge_Cuts.gbr --drill cpu-test.drl`

What happened:
The drill file includes G53 to interpret the Z position as machine coordinates:
`G53 G00 Z0.00000 (Retract)`
The mill and outline files are missing G53 and use work coordinates, crashing the bit into the PCB instead of retracting. The retract at the end of the file looks like the one in the drill file.
`G00 Z0.00000 (Retract to tool change height)`

What did you expect to happen:
G53 should be included in all retracts in all files when the option is enabled.

Please attach your input files and relevant output files and images.  **Don't forget to include your millproject file and gerbers!**
[gbr.zip](https://github.com/pcb2gcode/pcb2gcode/files/3121861/gbr.zip)

**Comment by eyal0** [comment]
I think that this is fixed now.
