### ISSUE TITLE
cutting of non outlines breaks copper milling

### ISSUE THREAD

**Issue by johnqube** [pcb2gcode/pcb2gcode#318]
Hello

running 1.3.2
I am facing something maybe related or duplicate of #7 and #237 
I am trying to cut shapes inside a PCB without cutting the PCB outline (the shape of my PCB is already at the correct dimensions, no need to cut the outlines)
when adding the outline layer, this breaks the milling of the copper layers
it looks like the computation of the outlines makes a very small bounding box cropping all the other layers.

you may look a the produced files attached
[plot.zip](https://github.com/pcb2gcode/pcb2gcode/files/3317776/plot.zip)

thank you

**Comment by eyal0** [comment]
Please send the command-line that you used to run this.  Thanks.

**Comment by eyal0** [comment]
Also, 1.3.2 is very old.  Can you run a newer version?  Please output your version number by typing `pcb2gcode --version`.

**Comment by eyal0** [comment]
Long time without a comment and the old code was old.
