### ISSUE TITLE
Why milling outline the board

### ISSUE THREAD

**Issue by Bastler100** [pcb2gcode/pcb2gcode#320]
Hello,
I am using 1.3.2 with the GUI. My layoutsoftware is SprintLayout. When I convert the gerbers to ngc-files there are milling paths outside the board. I want to use voronoi but voronoi does not work.
I set the toolpath offset to 10mm, so its like voronoi.
Sorry i am not able to built binaries from newer sources for windows.
Can someone help me
Hans

**Comment by Bastler100** [comment]
Hello,
when I not use "Vectorial Core" there are no milling path outline the board.
Thanks
Hans

**Comment by eyal0** [comment]
Can you use a newer version of pcb2gcode without GUI?

**Comment by eyal0** [comment]
Long time no reply.  Re-open if there are further issues.
