### ISSUE TITLE
pcb2gcode uses all extra-passes for outlines adjacent to pcb frame

### ISSUE THREAD

**Issue by AlexeyGusev** [pcb2gcode/pcb2gcode#321]
$ pcb2gcode --version
2.0.0
Git commit: v2.0.0-102-g6b71101
Boost: 106700
Gerbv: 2.7.0

This issue might be related to issue #237 (probably a remnant of incomplete fix).

Suppose you have a board like this (gerber file: [untitled-Bottom.gbr.gz](https://github.com/pcb2gcode/pcb2gcode/files/3496878/untitled-Bottom.gbr.gz)):
![Снимок экрана от 2019-08-13 15-08-22](https://user-images.githubusercontent.com/3841261/62940447-49cae800-bddc-11e9-9f7b-43301381fec5.png)

And you run this command:
`pcb2gcode --front untitled-Top.gbr --back untitled-Bottom.gbr --drill untitled-PTH.drl --outline untitled-Edge.Cuts.gbr`
with these essential parameters in millproject file:
```
mill-diameters=1.5mm,0.8mm,0.6mm,0.1mm
milling-overlap=10% 
metric=true                     # all settings in mm and derivatives (mm/min)
vectorial=true
optimise=true
metricoutput=true
zero-start=true                # Coordinates will be between (0,0) and (max_x_value, max_y_value)
extra-passes=10                 # Ignored when voronoi is in use
```
pcb2gcode generated this g-code: [back.ngc.gz](https://github.com/pcb2gcode/pcb2gcode/files/3496898/back.ngc.gz) which contains milling with all available tools. I have split this g-code file and loaded single tool sections to CNC software. Image below shows what CNC will do with 0.1mm bit:
![Снимок экрана от 2019-08-13 15-19-02](https://user-images.githubusercontent.com/3841261/62941102-ecd03180-bddd-11e9-9c24-4739ea8d9c7f.png)
and this is what CNC will do with 0.6mm bit:
![Снимок экрана от 2019-08-13 15-21-27](https://user-images.githubusercontent.com/3841261/62941163-125d3b00-bdde-11e9-96da-bddbb0266cd0.png)
It's easy to see here how pcb2gcode uses all available extra-passes to do excessive and unnecessary milling for upper-left, upper-right corners and a row of vias in the right part of the board. Big vias have clearance of 2mm and other vias have clearance of 0.8mm. They are actually taken care of by 0.8 mm and 1.5 mm tools listed in millproject file, just like all other clearances and thermals. But for outlines that are adjacent to pcb edges, I assume that this unnecessary milling with small tools is done by pcb2gcode because the milling outline is connected to outline around pcb. Other outlines that are inside the board and are not connected to outline around pcb are not affected by this bug.

**Comment by eyal0** [comment]
I'm able to see the same problem.  I'll take a look.
