### ISSUE TITLE
G64 and bCNC

### ISSUE THREAD

**Issue by danst0** [pcb2gcode/pcb2gcode#35]
bCNC and my GRBL seem to have a problem with the G64 commands. Sed helps:
`
sed -i.bak '/G64/d' ./ZProbe_front.nc
`

There is a g64 option, however g64=0 does not seem to leave them out

**Comment by corna** [comment]
g64=0 means "move with zero tolerance", which can be different from the default settings of the control software
I'll add a way to remove the G64 code, either by setting g64 to a negative value or by a new option

**Comment by corna** [comment]
Done in commit 8e61042c32735277e3039ceac05dd0d1f30dcf1b
_--g64_ has been replaced with _--tolerance_, and I've added the option _--nog64_ to disable the G64 code
