### ISSUE TITLE
Add option to turn off Voronoi isolation algorithm

### ISSUE THREAD

**Issue by emiliojazz** [pcb2gcode/pcb2gcode#36]
Hello,
is possible to turn off the Voronoi isolation algorithm and so have a GCODE that exactly resembles the original PCB? Without optimizations, so for example the text lines would also be visible.

**Comment by corna** [comment]
I don't understand what you mean with "turn off the Voronoi isolation algorithm", but if you want a gcode that represents the original Gerber you can use `--vectorial --offset=0` (but why?)
