### ISSUE TITLE
The tiling feature is broken

### ISSUE THREAD

**Issue by koppi** [pcb2gcode/pcb2gcode#39]
See screenshot from my [arduino-shield](https://github.com/koppi/arduino-shield) repo:

![pcb2gcode-tiling](https://cloud.githubusercontent.com/assets/9458631/16359934/90dee988-3b37-11e6-9b7a-d00d964e7cab.png)

Command-line was:
```bash
$ pcb2gcode --tile-x=2 --tile-y=2 --basename=ngc/arduino-shield --drill=arduino-shield.drl --front=arduino-shield-F_Cu.gbr --back=arduino-shield-B_Cu.gbr --outline=arduino-shield-Cmts_User.gbr --output-dir=. --postamble=ngc/postamble.ngc --preamble=ngc/preamble.ngc --dpi=1000 --metric=true --metricoutput=true --mirror-absolute=false --optimise=true --zchange=40.0000 --zero-start=true --zsafe=0.5000 --extra-passes=0 --mill-feed=600 --mill-speed=10000 --offset=1.0 --zwork=-0.075 --drill-feed=1000 --drill-front=true --drill-speed=20000 --milldrill=false --nog81=false --onedrill=true --zdrill=-2.0 --cut-front=true --cut-feed=600 --cut-infeed=10.0000 --cut-speed=10000 --cutter-diameter=2.0000 --fill-outline=true --outline-width=1 --zcut=-1.6500 --al-back=false --al-front=false --al-probefeed=100 --al-x=10.0000 --al-y=10.0000 --software=LinuxCNC
```

**Comment by corna** [comment]
I can't reproduce the bug with pcb2gcode 1.3.0 or HEAD and the command you posted, are you sure you're using the latest version?

![screenshot from 2016-06-26 09-53-17](https://cloud.githubusercontent.com/assets/6459604/16361118/3e60cf26-3b84-11e6-83e9-19bdc7d19bb3.png)

**Comment by koppi** [comment]
Seems to be only an issue in the development version of https://github.com/CauldronDevelopmentLLC/CAMotics then, closing.
