### ISSUE TITLE
2 sided board issues

### ISSUE THREAD

**Issue by zoomzoomluke** [pcb2gcode/pcb2gcode#4]
Hi,

Thanks for your excellent work.  I am however having a bit of a problem with producing double sided boards. Attached is my mill project file and some screenshots.
Basically when the AL probing happens on the back layer, the probing occurs in the incorrect place.

I'm not sure but I think that there may also be an issue with the units? The drilling shows different dimensions to the engraving.

![screen shot 2015-03-28 at 19 43 15](https://cloud.githubusercontent.com/assets/4789750/6882606/23552794-d583-11e4-899c-b8b69b76c527.png)
![screen shot 2015-03-28 at 19 43 35](https://cloud.githubusercontent.com/assets/4789750/6882609/23811980-d583-11e4-8d07-d91ac7e3fbc7.png)
![screen shot 2015-03-28 at 19 43 50](https://cloud.githubusercontent.com/assets/4789750/6882607/237a797c-d583-11e4-8e7e-b9707863dd24.png)
![screen shot 2015-03-28 at 19 44 14](https://cloud.githubusercontent.com/assets/4789750/6882608/237d5962-d583-11e4-99f9-b2372de89b59.png)

millproject:

# Common options
dpi=1000
metric=true
metricoutput=true
mirror-absolute=true
optimise=true
zchange=10.0000
zero-start=false
zsafe=2.0000

# Mill options
extra-passes=0
mill-feed=600
mill-speed=10000
offset=0.1
#offset=25  # Uncomment (and comment the previous line) for voronoi regions
zwork=-0.085

# Drill options
drill-feed=600
drill-front=false
drill-speed=10000
milldrill=false
nog81=false
onedrill=true
zdrill=-1.65

# Outline options
bridges=5
bridgesnum=2
cut-feed=400
cut-front=false
cut-infeed=0.4
cut-speed=10000
cutter-diameter=0.8
fill-outline=false
outline-width=0.2
zcut=-1.65

# Autoleveller options
al-back=true
al-front=true
al-probefeed=300
al-x=10.0000
al-y=10.0000
software=LinuxCNC

**Comment by zoomzoomluke** [comment]
Here are the project files:
https://www.dropbox.com/s/lch4x3tmol7479h/project_files.zip?dl=0

**Comment by Corna** [comment]
Which branch are you using?

**Comment by zoomzoomluke** [comment]
currently on master

**Comment by Corna** [comment]
If you open _drill.drd_ in text mode you'll see a _M72_ line: according to the [official excellon specifications](http://www.excellon.com/manuals/program.htm), _M72_ means "Inch Measuring Mode", so I suppose that your CAD software is exporting the gerber files in metric mode and the drill file is imperial mode.

**Comment by Corna** [comment]
With the new autoleveller version it works in my simulator. Try it

**Comment by zoomzoomluke** [comment]
Great that worked fine.

By default eagle outputs all gerbers and drills imperial. It's difficult to change this without hacking the eagle.def file.

Perhaps an option --x-format=imperial or --x-format=metric could be implemented? This would allow for different measuring mode inputs than the program's working units? 

Oh and just another strange problem. The milldrill option is resulting in the following error.
![screen shot 2015-03-30 at 09 28 18](https://cloud.githubusercontent.com/assets/4789750/6892817/23885992-d6bf-11e4-918d-345168b50812.png)

Thanks so much for your help :)

**Comment by Corna** [comment]
Here's a screenshot of your front + drill in the latest (git) gerbv
![screenshot from 2015-03-31 09 21 47](https://cloud.githubusercontent.com/assets/6459604/6914121/9e6e2204-d787-11e4-8f76-5968eb6b06c8.png)
As you can see gerbv fails to detect the real size of your drill file
Can you please check that the exported drill file is correct?

The milldrill bug is known, the milldrill option has always been broken, maybe I'll fix it after the work on autoleveller

**Comment by zoomzoomluke** [comment]
All working now, thanks. Turns out eagle 7.2+ made a change to the CAM processor and needed updated files.

Thanks for all your help.

**Comment by Corna** [comment]
Btw, milldrill functionality has been fixed in commit 9d3785b2b067075a6ecbae24ee3a7c5929acf18a
