### ISSUE TITLE
Only optimize at the end

### ISSUE THREAD

**Issue by eyal0** [pcb2gcode/pcb2gcode#425]
> No, I do mean remilling the same path. There are a lot of situations where I see the CNC doing a z lift, and *tiny* (like, maybe a mill diameter or two), then a z lower, where it *could* probably have just followed a section of milled path more directly (or otherwise passed through a previously milled space). I find that this is most noticeable when a smaller milling bit is "cleaning up" areas a larger mill can't cut.

> What do you think?

_Originally posted by @c- in https://github.com/pcb2gcode/pcb2gcode/issues/413#issuecomment-640053841_

**Comment by eyal0** [comment]
Uh-oh, I see something bad in the gcode.  Looks like the bg::simplify is running too many times.  Because of how the [simplify algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm) works, if you simplify two lines that overlap, you can get two lines that *almost* overlap.  For pcb2gcode, that looks like two paths that run next each other, sometimes overlapping, sometimes crossing, just by a little.

That's horrible for the euler path because it causes the mill head to wind around a bunch and zipzag trying to capture all these little lines!  Worse yet, it'll often have to lift and lower to deal with it.  That sucks really bad.

I'll try to only optimize at the end and hopefully that will solve the issue.

**Comment by c-** [comment]
Whoa... that *dramatically* cleans up that via test case.

![via-less-opt](https://user-images.githubusercontent.com/1276624/84534215-86df5f80-acb7-11ea-918c-ff3de3db0142.png)

... and for a less trivial board... well, here's the bCNC statistics before and after:

![stats_before](https://user-images.githubusercontent.com/1276624/84535189-4d0f5880-acb9-11ea-9ad1-ed95b0cacd7d.png)
![stats-after](https://user-images.githubusercontent.com/1276624/84535925-c52a4e00-acba-11ea-9fc3-9d0af34f9cfc.png)

At first glance, that seems to eliminate most of the sharp direction changing that was the impetus for #417.

**Comment by eyal0** [comment]
Yup, just wait until the backtracking is in place, it'll do a lot less retracting.
