### ISSUE TITLE
Pre drill during etch

### ISSUE THREAD

**Issue by fcobcn** [pcb2gcode/pcb2gcode#53]
Would it be possible to add a pre drill pass to the etch file?
Something like what eagle pcbgcode does, this helps to avoid the drill from slipping on the pcb.
I will be happy to buy the developer some beers for this functionality.

**Comment by corna** [comment]
It's not easy to add, but it is a useful functionality, I'll try to implement it
Beers are always appreciated :)

**Comment by eyal0** [comment]
@fcobcn What if you just set a shallow drilling depth and then run the drill.ngc file?  That would pre drill the holes, right?

**Comment by fcobcn** [comment]
@eyal that’s a good workaround. Thanks for the idea

**Comment by eyal0** [comment]
@fcobcn Is that workaround enough?  Can we close this issue?

**Comment by fcobcn** [comment]
@eyal0 Haven't tried yet, but should work OK.
