### ISSUE TITLE
How can you reduce the number of decimal places

### ISSUE THREAD

**Issue by Dimitry-Muzi** [pcb2gcode/pcb2gcode#54]
Hello. And how can you reduce the number of decimal places, or to round them? Thank you.

**Comment by corna** [comment]
Hi
[of.precision in ngc_exporter.cpp](https://github.com/pcb2gcode/pcb2gcode/blob/master/ngc_exporter.cpp#L163), but why?

**Comment by Dimitry-Muzi** [comment]
Many thanks. The fact that at such high resolution steps have to strongly crush driver. Otherwise, gradually lost the real coordinates.
