### ISSUE TITLE
How to remove -G04 P0?

### ISSUE THREAD

**Issue by Dimitry-Muzi** [pcb2gcode/pcb2gcode#56]
How to remove -G04 P0 (dwell for no time - G64 should not smooth over this point) -, since bCNC not understand it?

**Comment by Dimitry-Muzi** [comment]
Thank you is not necessary - has already found. )

**Comment by a-sheng** [comment]
How to remove -G04 P0 (dwell for no time - G64 should not smooth over this point)-,Use 
 bCNC
