### ISSUE TITLE
Autoleveller sporadically produces invalid g-code

### ISSUE THREAD

**Issue by ndilieto** [pcb2gcode/pcb2gcode#582]
The autoleveller produces invalid g-code with numbers in exponential format, when these are very close to zero: for example

> o1 call [2.54e-05] [13.2632] [-0.08]

This can be fixed by https://github.com/pcb2gcode/pcb2gcode/pull/580/commits/3660f6bbea6557995c2e8492fe4395f4d99eb344

**Comment by eyal0** [comment]
Fixed by #583
