### ISSUE TITLE
silently fails when output directory (output-dir) does not yet exist

### ISSUE THREAD

**Issue by Dromantor** [pcb2gcode/pcb2gcode#639]
## Description of bug:
The program silently fails to produce any output files when the output directory set by the "output-dir" setting does not yet exist. From the command line output it looks like everything succeeded. After creating said directory everything works fine.

## What did you try (include command-line arguments):
Just configure a output-dir and run the program without creating said dir first.

## What happened:
Directory is not created and no gcode files are produced.

## What did you expect to happen:
Directory should be created when it doesn't yet exist, or at the very least display an error.

## pcb2gcode version (run pcb2gcode --version to see this):
Built myself from version @ commit 5a93919d66922a75b1bcc273014f112d387512e3 (the current one per 2022-09-27) in WSL Ubuntu 22.xx.
```
2.5.0
Git commit: latest-5-g5a93919d
Boost: 107400
Gerbv: 2.9.3-dev~998b37
Geos: 3.12.0dev
```

## Speculation:
I guess when opening a file via std::ofstream::open(...) (ngc_exporter.cpp:256, drill.cpp:268+577) no non-existing directories in the path are created, so the file isn't either. Since the resulting ofstream instance is still valid and .is_open() is never checked it just works as if the file was open.

**Comment by Patronics** [comment]
This issue is still applicable with the latest released version (2.5.0), will an update be released anytime soon?
