### ISSUE TITLE
What does --vectorial do?

### ISSUE THREAD

**Issue by sybrenstuvel** [pcb2gcode/pcb2gcode#659]
Hello,

I can't seem to find what the `--vectorial` option does. The help text ("enable or disable the vectorial rendering engine") doesn't mean much if you don't already know what it's for.

The wiki also doesn't seem to describe this option.

**Comment by eyal0** [comment]
It's no longer an option, it's mandatory.

There used to be two ways to generate the shapes, now there is just one.

**Comment by sybrenstuvel** [comment]
Hah, ok, good to know thanks.
