### ISSUE TITLE
Error: Safety height not specified

### ISSUE THREAD

**Issue by MaartenHeuv** [pcb2gcode/pcb2gcode#73]
I really hope to make use of pcb2gcode, but I can't find a good manual and/or examples.
When I run >pcb2gcode test.gbr I get "Error: Safety height not specified"
My *.gbr files I create with Kicad

**Comment by MaartenHeuv** [comment]
Sorry, sorry, sorry:
In the mean time I found the manual, and gave the correct input to generate an ngc file.

Thanks an awful lot for this great job, it's a very nice piece of work !!!

**Comment by corna** [comment]
Glad to see you've already solved the problem.

Thanks!
