### ISSUE TITLE
Feature Request :: Variable delay (G4 Pn) or pause/manual-cycle-continue (M0) after starting spindle (M3)

### ISSUE THREAD

**Issue by WebMaka** [pcb2gcode/pcb2gcode#85]
My CNC mill uses a 3/4 HP DC motor for its spindle, which is operated by a motor controller board that's linked to my CNC controller PC. It's beastly (it can cut mild steel) but accurate enough to cut 8-mil traces. Problem is, it takes about 5 seconds to spin up.

I've been manually adding M0 (pause) lines after M3s, so program operation stops until the spindle can get up to speed. It'd sure be nice to have the option to automagically add them (or a settable delay, which is "G4 Px" where the "x" is the delay time in seconds).

EDIT: Just saw someone else had posted this as issue #51, but I don't see where the version I had downloaded (1.3.2) has this as an option. Was this already added, and if so, as of which version?

**Comment by corna** [comment]
It was never merged, can you download [corna/pcb2gcode](https://github.com/corna/pcb2gcode/tree/master) and check if it works?

**Comment by eyal0** [comment]
@WebMaka Is this fixed now?  I see spinup-time and spindown-time options available now.

**Comment by WebMaka** [comment]
I'll have to grab the latest and give it a try - haven't had time to do anything with it lately due to meatworld work overload. :-(

**Comment by eyal0** [comment]
It's supposed it to work and it looks okay in testing.  I'm going to close this.  You can reopen if you find that it's not working.
