### ISSUE TITLE
mirror_absolute does not mirror absolute

### ISSUE THREAD

**Issue by maknoll** [pcb2gcode/pcb2gcode#87]
Hi,

If i am using 

    mirror-absolute=true
    zero-start=false

i expect the backside to be mirrored on the on the y-axis of the gerber, instead it is mirrored at the bounding box.

https://github.com/pcb2gcode/pcb2gcode/blob/538707c0980cadd1cc766084fb3d94d9239ce1eb/surface_vectorial.cpp#L114-L116

I made a dirty fix and changed it to

     const coordinate_type mirror_axis = mill->mirror_absolute ? 
     0 : 
     ((bounding_box.min_corner().x() + bounding_box.max_corner().x()) / 2); 

Now it does exactly what i want it to do, but will surely mess up if `zero-start=true`

the following image shows the back correctly mirrored with the fix applied

<img width="693" alt="bildschirmfoto 2018-01-25 um 22 57 55" src="https://user-images.githubusercontent.com/615631/35414681-7178445e-0223-11e8-9a89-4240547b476d.png">

Thanks for providing me awesome tools.

-Martin

**Comment by maknoll** [comment]
see PR #90

**Comment by eyal0** [comment]
I think that I've solved this with https://github.com/pcb2gcode/pcb2gcode/pull/110 .

Please check and let me know.  You can also merge the latest code into your PR: https://github.com/pcb2gcode/pcb2gcode/pull/91

Thanks!

**Comment by eyal0** [comment]
Now with mirror-axis option, you should have all the flexibility needed to make nice, 2-sided boards.  Please re-open this issue if you have any questions.  Thanks!
