### ISSUE TITLE
Intermediate images left on disk

### ISSUE THREAD

**Issue by ryansturmer** [pcb2gcode/pcb2gcode#89]
It looks like there are a bunch of intermediate files generated when pcb2gcode is run - is there a way to get pcb2gcode to tidy up after itself, or to generate those files in a system-designated temporary directory instead?

**Comment by corna** [comment]
With _--output-dir_ you can specify the folder where all the images will be created.

**Comment by corna** [comment]
But in that case also the output gcode files would be placed in the temporary folder, which is not good
I can add an option like _--no-img_ I suppose

**Comment by eyal0** [comment]
Does it make sense to add yet another option for just this, however?  The
svg files are created in many places so the solution might be mess in code.

But the problem could be solved by just typing:

`pcb2gcode && rm -f *.svg`

That seems like a good enough solution...

**Comment by corna** [comment]
@eyal0 Valid point

**Comment by eyal0** [comment]
@ryansturmer Will the solution mentioned above suffice?  Just `rm -f *.svg` after each run.

**Comment by eyal0** [comment]
Re-open this if it's still a problem.
